name: Patrick Hart Fitness
favicon: null
layout_spectrum: 0.83989
typography_spectrum: 0.8349599542561918
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fffffb'
    - '#ff0000'
    - '#c64200'
    - '#453b30'
  brandStrength: 0.19984152796678245
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
